development:
  adapter: postgresql
  encoding: utf8
  database: kal_development
  pool: 5
  username:
  password:

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: kal_test
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: kal_production
  pool: 5
  username:
  password:

cucumber:
  <<: *TEST
